# Using modern compose specification
services:
  queue_service:
    build:
      context: ./queue_service
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    volumes:
      - ./queue_data:/app/queue_data
    restart: unless-stopped
    environment:
      - QUEUE_CONFIG_PATH=/app/config.json
